FROM python:3.10-slim

RUN apt-get update && \
    apt-get install -y --no-install-recommends ca-certificates build-essential && \
    update-ca-certificates && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app/requirements.txt .

# --- FIX: bypass SSL verification for PyPI ---
RUN python -m pip install --upgrade pip setuptools wheel --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir
RUN pip install --trusted-host pypi.org --trusted-host files.pythonhosted.org --no-cache-dir -r requirements.txt

COPY app/ /app

EXPOSE 5000
CMD ["python", "app.py"]
